version: '2.1'

services:

  gateway.api:
    image: sportstore/gateway.api:${TAG:-latest}
    ports: - "8000:80"
    build:
      context: ./Services/Gateway/Gateway.Api
      dockerfile: Dockerfile    
      
  catalog.api:
    image: sportstore/catalog.api:${TAG:-latest}
    ports: - "5002:80"
    build:
      context: ./Services/Catalog/Catalog.Api
      dockerfile: Dockerfile    
    depends_on:
      - sql.data

  identity.api:
    image: sportstore/identity.api:${TAG:-latest}
    ports: - "8000:80"
    build:
      context: ./Services/Identity/Identity.Api
      dockerfile: Dockerfile    
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux:latest   
    environment:
      SA_PASSWORD: "Qwerty123"
      ACCEPT_EULA: "Y"